# Generated by Django 2.2.1 on 2019-05-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190430_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilitiesuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
