# Generated by Django 2.2.1 on 2019-06-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190509_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitiesuser',
            name='dark_theme',
            field=models.BooleanField(default=False, verbose_name='email address'),
        ),
    ]
