# Generated by Django 2.2 on 2019-04-30 11:33

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_edit', models.DateTimeField()),
                ('underpayment', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Underpayment')),
                ('amount_to_pay', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Amount to pay')),
                ('payments_last_mouth', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Payments last mouth')),
                ('to_pay', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='To pay')),
                ('housing_stock', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Housing Stock')),
                ('hws_thermal_energy_cp', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='HWS: Thermal energy CP')),
                ('hws_cold_water_cp', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='HWS: Cold Water CP')),
                ('cold_water_cp', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Cold Water CP')),
                ('sewage_cp', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Sewage CP')),
                ('electricity_cp', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Electricity CP')),
                ('special_account_for_overhaul', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Special account for overhaul')),
                ('home_heating', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Home Heating')),
                ('hws_thermal_energy', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='HWS: Thermal Energy')),
                ('hws_cold_water', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='HWS: Cold Water')),
                ('cold_water', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Cold Water')),
                ('sewage', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Sewage')),
                ('garbage_service', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Garbage service')),
                ('electricity', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Electricity')),
                ('intercom_maintenance', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Intercom Maintenance')),
                ('gate_maintenance', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Gate Maintenance')),
                ('cctv_maintenance', models.FloatField(help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='CCTV Maintenance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
