# Generated by Django 2.2 on 2019-04-30 12:30

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilities',
            name='cold_water_consumption',
            field=models.FloatField(default=0, help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Cold Water Consumption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilities',
            name='electricity_consumption',
            field=models.FloatField(default=0, help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Electricity Consumption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilities',
            name='hws_cold_water_consumption',
            field=models.FloatField(default=0, help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='HWS: Cold Water Consumption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilities',
            name='sewage_consumption',
            field=models.FloatField(default=0, help_text='Required. Only numbers greater than zero', validators=[core.validators.validate_price], verbose_name='Sewage Consumption'),
            preserve_default=False,
        ),
    ]
