# Generated by Django 2.2.1 on 2019-05-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_auto_20190430_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='date_last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
